Repository funniture-Project/funniture-be, pull requests merged in 2025-03, with the labels that each got.

#231 :art:[PR]2025/03/01 사용자별 주문 조회 페이징 처리 적용 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#232 :art:[PR]2025/03/01 관리자 예약정보 조회 페이징 처리 적용 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#234 :green_heart:[PR]2025/03/01 관리자 예약정보, 제공자별 예약, 사용자별 주문 조회 Swagger 수정 - 정은미:green_heart:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
Labels: 🔨Refactor🔨

#236 🌐✨[PR]2025/03/02 사용자 - 탈퇴자 권한 변경 쿼리 수정 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅

#239 :art:[PR]2025/03/02 주문별 상세페이지 API 수정(대여자 정보 추가) - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/DetailRentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/DetailRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDetailDTO.java
Labels: 🔨Refactor🔨

#240 🌐✨[PR]2025/03/02 제공자 전환 신청 반려 / 승인 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MailService.java
Labels: ✨Feature✨, 📅ToDo📅

#242 :art:[PR]2025/03/02 제공자별 조회 API 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerRentalViewDTO.java
Labels: 🔨Refactor🔨

#243 🌐✨[PR]2025/03/02 제공자 전환 신청 후, 심사 텍스트 출력 / 재신청 연결중 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/RejectedMessageDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅

#245 :sparkles:[PR]2025/03/02 예약대기 -> 예약완료로 상태 update - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#247 :art:[PR]2025/03/03 제공자 예약확정 API 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#251 ✨[PR] 2025/03/01 ~ 2025/03/02 챗봇 연결 및 favorite 오류해결 - 정예진 🐛
  funniture/src/main/java/com/ohgiraffers/funniture/chat/controller/ChatController.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/service/ChatService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#253 :sparkles:[PR]2025/03/03 예약 대기 -> 예약 취소로 상태 update - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#257 :sparkles:[PR]2025/03/03 운송장번호, 운송업체명, 예약진행상태 수정 - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#259 ✨[PR]2025/03/03 관리자 페이지 상세 정보 출력 - 김규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/PointUpdateDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#262 :sparkles: [PR] 2025/03/04 관리자 페이지 질문 관리 백 & 프론트 연결 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/chat/controller/ChatController.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/service/ChatService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#264 🐛✨[PR]2025/03/04 제공자 전환 storeNo 중복 검사 로직 추가 - 김규남 ✨🐛
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/OwnerRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: 🔨Refactor🔨, 📅ToDo📅

#267 🚚 [PR]2025/03/04 관리자 페이지 유저 정보 불러오는 로직 수정 - 김규남 🚚
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
Labels: 🔨Refactor🔨, ✅PR✅

#270 🌐✨[PR]2025/03/05 관리자 페이지 페이징 처리 로직 추가 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
Labels: ✨Feature✨, 📅ToDo📅

#272 :sparkles: [PR] 2025/03/05 관리자 페이지 챗봇 질문 관리 수정, 등록 완료 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/chat/controller/ChatController.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/entity/ChatEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dao/BasicChatRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dao/ChatDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dto/ChatDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/service/ChatService.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#274 :sparkles:[PR]2025/03/05 사용자의 사용중인 예약 조회 - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserActiveRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserActiveRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/ActiveRentalDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminRentalViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#278 ✨ [PR] 2025/03/05 상담중 여부 변경 완료 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#280 ⚡️[PR]2025/03/05 회원가입 시 포인트 삽입 추가 - 김규남 ⚡️
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
Labels: 🔨Refactor🔨

#282 🌐[PR]2025/03/05 상품 별 문의 조회 로직 수정 및 연결 - 김규남 🌐
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
Labels: 📅ToDo📅, ✅PR✅

#284 :art:[PR]2025/03/06 포인트 내역 조회 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
Labels: 🔨Refactor🔨

#288 :sparkles:[PR]2025/03/06 사용자 마이페이지 예약진행상태별 갯수 조회 API - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalStateCountRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalStateCountRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalStateCountDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#289 ✨[PR]2025/03/06 상품 문의 등록 로직 / 불러오는 로직 수정 - 김규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅

#292 🌐✨[PR]2025/03/06 제공자 마이페이지 문의 연결 로직 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
Labels: 🔨Refactor🔨, ✅PR✅

#293 🐛 [PR]2025/03/06 has_image 삭제 - 김규남 🐛
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
Labels: 🔨Refactor🔨

#295 ✨[PR] 2025/03/06 문의 사용자 목록 조회 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/entity/AdminInquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dao/AdminInquiryDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dao/AdminInquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/AdminInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/ConsultingListDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/service/AdminInquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#296 :zap: [PR] 2025/03/06 코드 수정 - 정예진 :zap:
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/AdminInquiryDTO.java
Labels: 🔨Refactor🔨, 📅ToDo📅, ✅PR✅

#303 :art:[PR]2025/03/07 배송지 수정 API update - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserActiveRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#304 🌐✨[PR]2025/03/07 제공자 문의 페이지 페이징 처리 로직 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
Labels: ✨Feature✨, 📅ToDo📅

#306 🌐✨[PR]2025/03/07 마이페이지 문의 데이터, 페이징 로직 완료 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/MemberInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
Labels: ✨Feature✨, 📅ToDo📅

#308 :art:[PR]2025/03/07 사용날짜,만료날짜 수정되게 예약진행상태 API 수정 -정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#311 ✨[PR]2025/03/08 리뷰 등록 로직 구현 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewRegistDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
Labels: ✨Feature✨, 📅ToDo📅

#313 🌐✨[PR]2025/03/08 사용자 리뷰 페이지 조회 및 페이징 로직 -김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
Labels: ✨Feature✨, 📅ToDo📅

#315 🌐✨[PR]2025/03/08 리뷰 데이터 제품 상세페이지 연결 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
Labels: ✨Feature✨, 📅ToDo📅

#318 :sparkles: [PR] 2025/03/08 1:1문의 완성 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/entity/AdminInquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dao/AdminInquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/ConsultingListDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/service/AdminInquiryService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#319 :sparkles:[PR]2025/03/09 관리자페이지 매출현황 조회 API - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminSalesEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminSalesDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#321 ✨ [PR] 2024/03/09 공지사항 조회, 등록, 삭제 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/notice/controller/NoticeController.java
  funniture/src/main/java/com/ohgiraffers/funniture/notice/entity/NoticeEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/notice/model/dao/NoticeRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/notice/model/dto/NoticeDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/notice/model/service/NoticeService.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#322 🐛[PR]2025/03/09 회원 가입 시 is_consulting 에러 수정 - 김규남 🐛
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
Labels: 🚫Error🚫

#325 :sparkles: [PR] 2025/03/09 제공자 업체정보 페이지 완성 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/OwnerController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/OwnerInfoService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#326 🌐✨[PR]2025/03/09 제공자 메인 페이지 / 리뷰 페이지 연결 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/OwnerReviewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
Labels: ✨Feature✨, 📅ToDo📅

#330 :sparkles:[PR]2025/03/09 제공자별 월별 매출 현황 조회 API - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminSalesDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerSalesDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalChartDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#333 :art:[PR]2025/03/10 제공자별 월별 정산관리 조회 예약번호 오름차순 추가 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
Labels: 🔨Refactor🔨

#334 🌐✨[PR]2025/03/10 사용자 페이지 리뷰 등록 로직 및 쿼리 수정 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
Labels: ✨Feature✨, 📅ToDo📅

#337 🌐✨[PR]2025/03/10 문의 답변 로직 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/entity/CommentEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dao/CommentRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dto/CommentRegistDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
Labels: ✨Feature✨, 📅ToDo📅

#339 :art:[PR]2025/03/10 예약 등록 시 할인율 적용 된 포인트 금액 차감& 포인트적립 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#341 :art:[PR]2025/03/10 관리자 정산 그룹화 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
Labels: 🔨Refactor🔨

#343 ✨ [PR] 2025/03/10 접속자 수 반영 및 조회 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/chat/screenshot.png
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/CountCombinedKey.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/CountEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/CountRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/ConnectCountDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CountNumService.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductWithPriceDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#345 :sparkles:[PR]2025/03/11 제공자/관리자 마이페이지 메인 차트 데이터 - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerCurrentMonthSalesRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerCurrentMonthSalesRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerMonthlySalesRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerMonthlySalesRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/SalesRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/SalesRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminMonthlySalesDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/CurrentMonthSalesDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/MonthlySalesDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/UserOrderViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#347 :art:[PR]2025/03/11 반납완료로 상태 업데이트 시 used_stock 예약갯수에 따라 감소 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#348 :bug: [PR] 2025/03/11 응답 상태코드 변경 - 정예진 :bug:
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
Labels: 🔨Refactor🔨

#350 :sparkles:[PR]2025/03/11 제공자의 예약진행상태 카운트 API - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalStateCountRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalStateCountRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#352 🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 사용자 페이지 연결 / 상세 보기 로직 / 리뷰 쿼리 수정 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dao/CommentRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dto/CommentByMyPageDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/MemberInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅

#354 :sparkles:[PR]2025/03/11 제공자의 마이페이지 만료기간별 카운트 API-정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerPeriodCountRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerPeriodCountRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalMapper.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalPeriodCountDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/UserOrderViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
  funniture/src/main/resources/mappers/rental/RentalMapper.xml
Labels: ✨Feature✨

#355 ✨ [PR] 2025/03/11 카테고리별 상품 개수 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserActiveRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/ActiveRentalDTO.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#356 🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 상세페이지 연결 로직 - 김규남✨ 🌐
  funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/entity/CommentEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dao/CommentRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dto/CommentByProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
Labels: ✨Feature✨, 📅ToDo📅

#358 :sparkles:[PR]2025/03/12 업체 매출 TOP5 API - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerTopDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#361 🌐✨[PR]2025/03/12 제공자 마이페이지 평균 리뷰 별점 조회 로직 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewAvgScoreDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
Labels: ✨Feature✨, 📅ToDo📅

#362 점검중
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CountNumService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#363 :art:[PR]2025/03/12 찜 group by 추가&예약취소 시 포인트 반환 및 이벤트 포인트 반환 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDetailInfoDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#364 :art:[PR]2025/03/13 예약취소 시 결제금,포인트적립금 반환 부분 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
Labels: 🔨Refactor🔨

#365 📝[PR]2025/03/13 sout 구문 삭제 , 주석 삭제 -김규남 📝
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthFailUserHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/interceptor/JwtTokenInterceptor.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
  funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MailController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/OwnerController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MailService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
  funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewAvgScoreDTO.java
Labels: ✅PR✅

#366 :memo: [PR] 2025/03/13 console 정리 - 정예진 :memo:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
Labels: 🚫Error🚫, 🔨Refactor🔨, 📅ToDo📅, ✅PR✅

#367 정산 회원명 수정
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerSalesDTO.java
Labels: 🔨Refactor🔨

#388 제공자 예약 상세페이지 이미지 수정
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerRentalViewDTO.java
Labels: 🔨Refactor🔨

#389 yml 수정
  funniture/src/main/resources/application.yml
Labels: 🔨Refactor🔨

#390 관리자 페이징처리 수정(전체카운트 수정)
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
Labels: 🔨Refactor🔨
