Repository funniture-Project/funniture-be, pull requests merged in 2025-02, with the labels that each got.

#8 :art: feature/findRentalAllListByAdmin & MapperScan추가_eunmi
  funniture/src/main/java/com/ohgiraffers/funniture/config/BeanConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalMapper.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/PostAddressDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/ProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
  funniture/src/main/resources/mapper/rental/RentalMapper.xml
  funniture/src/main/resources/mappers/product/ProductMapper.xml
  funniture/src/main/resources/mappers/rental/RentalMapper.xml
Labels: ✨Feature✨

#9 :recycle:feature/findRentalAllListByAdmin_modify_eunmi
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/CategoryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
  funniture/src/main/resources/mappers/rental/RentalMapper.xml
Labels: 🔨Refactor🔨

#11 Feature/product 250202 yejin [특정 상품 조회 및 대여 조건 조회 연결]
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/CategoryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/CategoryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductMapper.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/RentalOptionInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
Labels: ✨Feature✨, ✅PR✅

#16 :memo: join select 은미님 참고 자료 :memo:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductWithPriceDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, ✅PR✅

#18 :sparkles: 사용자 렌탈상품 예약
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalInfo.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalMapper.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminRentalViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
  funniture/src/main/resources/mappers/rental/RentalMapper.xml
Labels: ✨Feature✨

#19 :art: 코드 구조 변경 :art:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductWithPriceDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: 🔨Refactor🔨, ✅PR✅

#21 Feature/product byowner yejin [제공자별 상품 조회 추가]
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithOptionEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDetailDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, ✅PR✅

#22 :sparkles: admin-select-Entity 추가
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminCategoryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminOwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
Labels: ✨Feature✨

#25 :sparkles: 관리자 예약정보 조회 추가
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminRentalViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/CategoryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/PostAddressDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/ProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalOptionInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#27 :sparkles: 사용자 주문/배송 조회 Rest-API 추가
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserRentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserRentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/UserOrderViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#28 :art: productService 구조 변경 :art:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: 🔨Refactor🔨, ✅PR✅

#47 :sparkles:250202 관리자 예약 조건별 조회 및 전체조회_eunmi
  funniture/build.gradle
  funniture/src/main/java/com/ohgiraffers/funniture/config/QuerydslConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminOwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminRentalSearchCriteria.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#53 ⚡[ PR ] 2025/2/12 product 구조 dsl로 변경 및 swagger 작성 🎨
  funniture/build.gradle
  funniture/src/main/java/com/ohgiraffers/funniture/common/ProductSearchCondition.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Inquiry.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Product.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminOwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
Labels: 🔨Refactor🔨, ✨Feature✨, ✅PR✅

#54 :sparkles:[PR]2025/02/12 사용자 예약정보 조회&주문일날짜 필터링 조회-정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserRentalEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserRentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminRentalViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#62 :green_heart:[PR]2025/02/12 Swagger 추가-정은미:green_heart:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
Labels: 🔨Refactor🔨

#64 💚 [PR]2025/02/12 문의 Rest_API(Swagger) 작성-김규남💚
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
Labels: 🔨Refactor🔨

#72 :sparkles:[PR]2025/02/13 사용자별 예약조회-정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#73 :wrench: [PR]2025/02/13 DTO 및 엔티티 생성 -김규남 :wrench:
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryRegistEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/RegistRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
Labels: 🔨Refactor🔨

#74 :wrench: [PR]2025/02/13 Rest-api 설계 테스트 및 파일 구조 변경-김규남 :truck:
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
Labels: 🚫Error🚫, 🔨Refactor🔨

#75 :art:[PR]2025/02/12 예약등록&응답데이터&swagger 수정-정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#76 :sparkles:[PR]2025/02/13 사용자별 배송지 조회-정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dto/DeliveryAddressDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
Labels: ✨Feature✨

#83 ✨[PR]2025/02/14 스프링 시큐리티 회원가입 - 중간 커밋 -김규남 ✨
  .gitignore
  funniture/build.gradle
  funniture/src/main/java/com/ohgiraffers/funniture/config/webSecurityConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberRoleDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
Labels: ✨Feature✨

#82 🎨 [PR] 2025/2/14 refcategory 별 검색 되도록 수정 [정예진]🎨
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductWithPriceDTO.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#84 ✨[PR]2025/02/14 회원가입(encoder / postman 이용) - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/config/webSecurityConfig.java
Labels: ✨Feature✨

#86 :truck: 📝 [PR]2025/02/14 로그인을 위한 spring 시큐리티 설정 및 jwt 토큰 설정 -김규남 📝 :truck:
  funniture/build.gradle
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/HeaderFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthFailUserHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/interceptor/JwtTokenInterceptor.java
  funniture/src/main/java/com/ohgiraffers/funniture/common/AuthConstants.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/webSecurityConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/TokenDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
  funniture/src/main/java/com/ohgiraffers/funniture/util/ConvertUtil.java
  funniture/src/main/java/com/ohgiraffers/funniture/util/TokenUtils.java
  funniture/src/main/resources/application.yml
Labels: ✨Feature✨

#91 :zap: [PR] 2025/2/15 카테고리별 제공자 조회 추가 및 수정 [정예진] :zap:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
Labels: 🔨Refactor🔨, 📅ToDo📅

#93 🐛✨ [PR]2025/02/16 postman을 이용한 로그인 검증 -김규남 🐛✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
Labels: 🚫Error🚫, ✨Feature✨

#94 :ambulance: 긴급 : 접근 권한 수정 :ambulance:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
Labels: 🔨Refactor🔨

#96 📝[PR]2025/02/16 로그인 구현중 (충돌 날까봐 중간 머지) - 김규남 :white_check_mark:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
  funniture/src/main/java/com/ohgiraffers/funniture/util/TokenUtils.java
Labels: 🚫Error🚫, 🔨Refactor🔨, ✅PR✅

#101 :green_heart:[PR]2025/02/17 deliveryaddress 스웨거 추가&관리자 검색조건 rentalNo 수정-정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
Labels: 🔨Refactor🔨

#102 ✨[PR]2025/02/17 postman을 이용하여 로그인 완료 (토큰 정보 반환) - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
Labels: ✨Feature✨, ✅PR✅

#104 ✨ [PR] 2025/2/17 제품 검색 조건 판매 상태 추가 + 전체 업체 조회 추가 [정예진] ✨
  funniture/src/main/java/com/ohgiraffers/funniture/common/ProductSearchCondition.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#105 ✨[PR]2025/02/17 프론트-백엔드 로그인 연결 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/HeaderFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
Labels: ✨Feature✨, ✅PR✅

#107 :sparkles: [PR]2025/02/17 제공자별 예약 조회&만료일 필터링-정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerRentalViewDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#111 ✨[PR]2025/02/18 프론트에 전달할 id, role 정보 삽입 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/TokenDTO.java
Labels: ✅PR✅

#114 :sparkles: 상품 상태 정보 수정 완료 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ChangeStatusDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#116 🔀 [PR] 2025/2/18 merge용 [정예진] 🔀
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductForDeleteRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅, 🤚Help🤚

#124 💚[PR]2025/02/19 문의 / 회원가입 / 로그인 swagger 추가 - 김규남💚
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
Labels: 📅ToDo📅

#125 💚[PR]2025/02/19 문의 / 회원가입 / 로그인 swagger 수정 - 김규남💚
  funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
Labels: 🔨Refactor🔨

#126 ⚡️ PR]2025/02/19 로그인 시, 백에서 프론트로 비밀번호 전달되지 않게 수정 - 김규남 ⚡️
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
Labels: ✨Feature✨, ✅PR✅

#127 :art:[PR]2025/02/19 사용자 예약등록 rentalNo 자동생성 부분 수정 및 Jwt 추가 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#133 :truck:[PR]2025/02/20 OwnerInfoEntity Member 로 파일 위치 변경 - 정은미:truck:
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDetailDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#135 ✨[PR]2025/02/20 이메일 요청 시, gmail로 인증 번호 발송 - 김규남 ✨
  funniture/build.gradle
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/MailConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MailController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MailService.java
  funniture/src/main/resources/application.yml
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#137 :art: [PR] 2025/02/20 productDetail 조회 내역 추가 -정예진 :art:
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDetailDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: 🔨Refactor🔨, 📅ToDo📅, ✅PR✅

#146 ✨[PR]2025/02/21 로그인 페이지 비밀번호 변경 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MailController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#147 :sparkles: [PR] 2025/02/21 상품 등록 + 이미지 cloudinary 업로드 - 정예진 :sparkles:
  funniture/build.gradle
  funniture/src/main/java/com/ohgiraffers/funniture/cloudinary/CloudinaryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/config/CloudinaryConfig.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithOptionEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
  funniture/src/main/resources/application.yml
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#153 ✨[PR]2025/02/23 사용자 마이페이지 비밀번호 인증 - 김규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#158 :sparkles:[PR]2025/02/23 신규배송지 등록 & 스웨거 & doFilterInternal 에 경로 추가 -정은미:sparkles:
  .github/ISSUE_TEMPLATE/error-template.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-issue.md
  .github/ISSUE_TEMPLATE/refactor-issue.md
  .github/ISSUE_TEMPLATE/to-do-list.md
  .github/pull_request_template.md
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
Labels: ✨Feature✨

#159 :sparkles:[PR]2025/02/23 배송지 수정 기능 , 스웨거 추가 및 배송지 등록 수정 - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dto/DeliveryAddressDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
Labels: 🔨Refactor🔨, ✨Feature✨

#161 :sparkles:[PR]2025/02/23 배송지 삭제 기능 스웨거 추가 및 조회 수정 -정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dto/DeliveryAddressDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
Labels: 🔨Refactor🔨, ✨Feature✨

#160 ✨[PR]2025/02/23 사용자 마이 페이지 정보 변경 및 불러오기 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#162 :sparkles:[PR]2025/02/23 보유 포인트 조회 기능, 스웨거 추가 - 정은미:sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointControllers.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointHistoryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointHistoryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointHistoryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
Labels: ✨Feature✨

#169 ✨[PR]2025/02/24 주소 정보 불러오기 위한 memberDTO / MemberEntity에 address 추가 - 김규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
Labels: 🔨Refactor🔨, 📅ToDo📅, ✅PR✅

#170 ✨[PR]2025/02/24 사용자 마이페이지에서 주소 변경 로직 / api 작성 - 김규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#172 :sparkles: [PR] 2025/02/25 상품 등록 예외처리 및 완성 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/common/PagingButton.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/RentalOptionInfoRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#173 :art:[PR]2025/02/24 포인트 API 수정(DB 수정) - 정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointControllers.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointHistoryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointHistoryRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointHistoryDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
Labels: 🔨Refactor🔨

#174 :twisted_rightwards_arrows: PointController 소스트리에서 잘못 삭제함 - 정은미:twisted_rightwards_arrows:
  funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointController.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
Labels: ✅PR✅

#176 :sparkles:[PR]2025/02/24 포인트 사용, 충전 내역 조회 API, 스웨거 추가 - 정은미:green_heart:
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointController.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
Labels: ✨Feature✨

#178 :sparkles:[PR]2025/02/24 사용자별 기본 배송지 조회, 스웨거 추가 -정은미:green_heart:
  funniture/package-lock.json
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
Labels: ✨Feature✨

#179 ✨[PR]2025/02/24 이미지 변경 로직 / 토큰 시간 수정 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
  funniture/src/main/resources/application.yml
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#180 ✨[PR]2025/02/24 사용자 마이페이지 탈퇴자 권한 변경 - 규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅

#182 ✨ [PR] 2025/02/24 상품 등록 및 수정 전면 수정완료 - 정예진✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/RentalOptionInfoRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/RentalOptionInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#186 ✨[PR]2025/02/25 회원가입 시 이메일 중복 여부 체크 - 규남 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
Labels: ✨Feature✨, 📅ToDo📅

#188 🎨 [PR] 2025/02/25 상품 등록 및 수정 be 수정 완료 - 정예진 🎨
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#190 :art:[PR]2025/02/25 상품 등록 API 수정 -정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#191 ✨[PR]2025/02/25 사용자에서 제공자 전환 등록 로직 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/OwnerController.java
Labels: ✨Feature✨, 📅ToDo📅

#196 :art:[PR]2025/02/26 제공자별 예약 내역 조회 API, 스웨거 수정 - 정은미:green_heart:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
Labels: 🔨Refactor🔨

#199 :art:[PR]2025/02/26 제공자별 예약조회 API(예약, 배송, 반납 탭별로 필터링), 스웨거 수정-정은미:green_heart:
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: 🔨Refactor🔨

#200 🌐 [PR]2025/02/26 관리자 페이지에 필요한 데이터 연결 - 김규남 🌐
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/PointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
Labels: ✨Feature✨, 📅ToDo📅

#203 :sparkles: [PR] 2025/02/26 최근 본 상품 완료 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/common/OrderByNull.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/RecentProductDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#204 ✨[PR]2025/02/26 관리자 페이지에서 모든 제공자 및 회원 불러오기 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberRoleDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoAndMemberDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
Labels: ✨Feature✨, 📅ToDo📅

#205 ✨ [PR] 2025/02/26 관심상품 조회 완성 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/controller/FavoriteController.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/entity/FavoriteCombinedKey.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/entity/FavoriteEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dto/FavoriteDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/service/FavoriteService.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#206 ✨[PR]2025/02/26 마이페이지 제공자 신청 로직 -김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/OwnerRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: 🔨Refactor🔨, 📅ToDo📅

#210 🌐✨[PR]2025/02/27 제공자 전환 데이터 불러오기 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerListDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
Labels: ✨Feature✨, 📅ToDo📅

#212 ✨[PR]2025/02/27 사용자 - 제공자 전환 신청 시 데이터 삽입 (image, pdf) - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/cloudinary/CloudinaryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅

#217 :sparkles: [PR] 2025/02/27 관심상품 전체 완료 - 정예진 :sparkles:
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/controller/FavoriteController.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDetailInfoDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDetailInfoRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteListRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dto/FavoriteDetailInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dto/FavoriteListDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/service/FavoriteService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅

#218 ✨[PR]2025/02/27 제공자 전환 신청 / 재신청 로직 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅

#219 :art: [PR]2025/02/27 공용 페이징처리 로직 구현-정은미:art:
  funniture/src/main/java/com/ohgiraffers/funniture/common/Criteria.java
  funniture/src/main/java/com/ohgiraffers/funniture/common/PageDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/common/Pagination.java
  funniture/src/main/java/com/ohgiraffers/funniture/common/PagingButton.java
  funniture/src/main/java/com/ohgiraffers/funniture/common/PagingResponseDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
  funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
Labels: ✨Feature✨

#220 ✨[PR]2025/02/27 관리자 페이지에 필요한 데이터 로직 - 김규남✨
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerListModalDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅

#224 🌐✨[PR]2025/02/28 관리자 페이지 권한 변경 로직 - 김규남 ✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
Labels: ✨Feature✨, 📅ToDo📅

#226 🌐✨[PR]2025/02/28 관리자 페이지 사용자 → 탈퇴자 권한 변경 - 김규남✨🌐
  funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
  funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
Labels: ✨Feature✨, 📅ToDo📅, ✅PR✅

#228 ✨[PR] 2025/02/28 API 생성 및 페이징처리 연결 - 정예진 ✨
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/entity/AdminInquiryEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/service/AdminInquiryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/controller/ChatController.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/entity/ChatEntity.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dao/ChatDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dao/ChatRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dto/ChatDTO.java
  funniture/src/main/java/com/ohgiraffers/funniture/chat/model/service/ChatService.java
  funniture/src/main/java/com/ohgiraffers/funniture/cloudinary/CloudinaryService.java
  funniture/src/main/java/com/ohgiraffers/funniture/common/ProductSearchCondition.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteListRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/service/FavoriteService.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
  funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
Labels: 🔨Refactor🔨, ✨Feature✨, 📅ToDo📅, ✅PR✅
